# Site wide configuration

title: MSP tech Blog
description: 글쓰기 - 제대로 쓰려 말고, 무조건 써라 (-제임서 서버)
logo: logo2.png
search: true
comments: true
url: //gabia.gitlab.io

# Jekyll configuration

permalink: /:categories/:title/
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
production: true # custom-made robots.txt uses this variable

# Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
kramdown:
  input: GFM
  syntax_highlighter: rouge
#  syntax_highlighter_opts:
#    # Rouge Options › https://github.com/jneen/rouge#full-options
#    css_class: 'highlight'
#    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
#    span:
#      line_numbers: false
#    block:
#      line_numbers: true
#      start_line: 1
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: gabia-Nathan
  avatar: nathan.png
  email: gabia@gmail.com
  disqus-shortname: # msp-blog
  twitter: gabia
  facebook: gabia
  # github: gabia
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
